//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group001Bookstore.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EconomicsBook
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Author { get; set; }
        public Nullable<int> Year { get; set; }
        public string CoverImagePath { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> UniqueId { get; set; }
    }
}
