//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group001Bookstore.MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Group001BookstoreEntities : DbContext
    {
        public Group001BookstoreEntities()
            : base("name=Group001BookstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CSBook> CSBooks { get; set; }
        public virtual DbSet<EconomicsBook> EconomicsBooks { get; set; }
        public virtual DbSet<NovelBook> NovelBooks { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ChildrenBook> ChildrenBooks { get; set; }
    
        public virtual ObjectResult<GetNovelBooksofPage_Result> GetNovelBooksofPage(Nullable<int> bookPerPage, Nullable<int> pageNumber)
        {
            var bookPerPageParameter = bookPerPage.HasValue ?
                new ObjectParameter("BookPerPage", bookPerPage) :
                new ObjectParameter("BookPerPage", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNovelBooksofPage_Result>("GetNovelBooksofPage", bookPerPageParameter, pageNumberParameter);
        }
    }
}
